phases:
- phase: VS_Latest

  steps:
  - checkout: self
    clean: true

  - powershell: './build/build.ps1 -script build/build.cake'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/build
      Contents: '*.nupkg'
      TargetFolder: $(Build.ArtifactStagingDirectory)/vslatest

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: $(Build.DefinitionName)
